import {
  AssessmentData,
  CarePlanAction,
  DiseaseRisk,
  Factor,
  RiskLevel,
} from '@/data/mockData';
import {
  BackendAssessmentResponse,
  BackendKeyFactor,
  BackendShapFactor,
  PatientInput,
} from '@/services/api';

const DISEASE_KEYS = ['heart_disease', 'kidney_disease', 'stroke'] as const;
type BackendDisease = (typeof DISEASE_KEYS)[number];
type FrontendDisease = 'heart' | 'kidney' | 'stroke';

const diseaseKeyMap: Record<BackendDisease, FrontendDisease> = {
  heart_disease: 'heart',
  kidney_disease: 'kidney',
  stroke: 'stroke',
};

const displayNames: Record<FrontendDisease, string> = {
  heart: 'Heart Disease',
  kidney: 'Chronic Kidney Disease',
  stroke: 'Stroke',
};

function toRiskLevel(level: BackendAssessmentResponse['ui']['overall_severity']): RiskLevel {
  return level.toLowerCase() as RiskLevel;
}

function diseaseRiskLevel(level: BackendAssessmentResponse['risk_overview'][number]['risk_level']): RiskLevel {
  return level.toLowerCase() as RiskLevel;
}

function exerciseDisplayDays(value: PatientInput['exercise_frequency']): number {
  switch (value) {
    case '1_2':
      return 2;
    case '3_4':
      return 4;
    case '5_plus':
      return 5;
    default:
      return 0;
  }
}

function shapFactorsForDisease(
  response: BackendAssessmentResponse,
  disease: BackendDisease,
): Map<string, BackendShapFactor> {
  const shap = response.shap?.[disease];
  const result = new Map<string, BackendShapFactor>();

  if (!shap) {
    return result;
  }

  for (const factor of [
    ...(shap.top_positive_factors ?? []),
    ...(shap.top_negative_factors ?? []),
  ]) {
    result.set(`${factor.feature}|${factor.direction}`, factor);
  }

  return result;
}

function factorFromBackend(
  response: BackendAssessmentResponse,
  item: BackendKeyFactor,
): Factor | null {
  const shapMap = shapFactorsForDisease(response, item.disease);
  const shapFactor = shapMap.get(`${item.feature}|${item.direction}`);

  // The backend's deterministic validation guarantees that an emitted key
  // factor should correspond to a supplied SHAP factor. Skip it rather than
  // inventing a numerical contribution if a malformed response reaches here.
  if (!shapFactor) {
    return null;
  }

  return {
    name: item.label,
    contribution: shapFactor.shap_value,
    direction: item.direction,
    importance: item.importance,
    explanation: item.explanation,
  };
}

function recommendationsForDisease(
  response: BackendAssessmentResponse,
  disease: BackendDisease,
): string[] {
  // Recommendations are intentionally global in the backend schema. We keep
  // the same verified list on each disease card instead of pretending that a
  // recommendation belongs exclusively to one disease.
  void disease;
  return response.recommendations.map((item) => item.title);
}

function buildRisk(
  response: BackendAssessmentResponse,
  disease: BackendDisease,
): DiseaseRisk {
  const overview = response.risk_overview.find((item) => item.disease === disease);
  if (!overview) {
    throw new Error(`Backend response is missing risk overview for ${disease}.`);
  }

  const factors = response.key_factors
    .filter((factor) => factor.disease === disease)
    .map((factor) => factorFromBackend(response, factor))
    .filter((factor): factor is Factor => factor !== null);

  return {
    disease: displayNames[diseaseKeyMap[disease]],
    riskPercentage: overview.risk_percent,
    riskLevel: diseaseRiskLevel(overview.risk_level),
    factors,
    recommendations: recommendationsForDisease(response, disease),
    headline: overview.headline,
    shortExplanation: overview.short_explanation,
    riskContext: overview.risk_context,
  };
}

function recommendationToCarePlan(
  response: BackendAssessmentResponse,
): CarePlanAction[] {
  return response.recommendations.map((item, index) => ({
    id: `rec-${index + 1}`,
    title: item.title,
    description: item.description,
    priority: item.priority,
    // These recommendations are generated by the HealthTwin AI agent. The
    // recommendation's backend `type` remains available in the response but
    // is not the same concept as UI provenance.
    type: 'ai-generated',
    completed: false,
  }));
}

export function mapBackendToFrontend(
  response: BackendAssessmentResponse,
  patient: PatientInput,
): AssessmentData {
  const lastUpdated = new Date().toISOString();
  const requestId = response.request_id ?? `local-${Date.now()}`;

  return {
    patient: {
      id: requestId,
      name: 'Patient',
      age: patient.age,
      gender: patient.sex === 'male' ? 'Male' : 'Female',
      height: patient.height_cm,
      weight: patient.weight_kg,
      smoking: patient.smoking_status === 'current',
      exerciseDaysPerWeek: exerciseDisplayDays(patient.exercise_frequency),
      lastUpdated,
    },
    overallRisk: toRiskLevel(response.ui.overall_severity),
    overallRiskSummary: response.overall_summary,
    risks: {
      heart: buildRisk(response, 'heart_disease'),
      kidney: buildRisk(response, 'kidney_disease'),
      stroke: buildRisk(response, 'stroke'),
    },
    // No genuine longitudinal forecast is returned by the backend yet.
    trajectory: [],
    carePlan: recommendationToCarePlan(response),
    labInsights: response.lab_insights,
    patientReport: response.patient_report,
    doctorSummary: response.doctor_summary,
    specialistFollowUp: response.specialist_follow_up,
    ui: {
      overall_severity: toRiskLevel(response.ui.overall_severity),
      headline: response.ui.headline,
      show_attention_banner: response.ui.show_attention_banner,
      priority_count: response.ui.priority_count,
    },
    requestId: response.request_id,
  };
}
