import sys
import json
sys.path.insert(0, './backend')
import asyncio
from ml.predict import predict_all
from explainability.explainer import explain_all

# A. healthy young patient
patient_a = {
    "age": 25, "sex": "male", "height_cm": 180, "weight_kg": 75,
    "smoking_status": "never", "exercise_frequency": "5_plus", "sleep_hours": 8,
    "alcohol_use": "never", "high_bp": False, "high_chol": False,
    "diabetes": "none", "kidney_disease": False, "copd": False,
    "depression": False, "difficulty_walking": False, "general_health": "excellent",
    "physical_unwell_days": 0
}

# Derived inputs for predict_all and explain_all
def to_ml_patient(pt):
    # Quick mock of ml_features generated by pipeline
    p = dict(pt)
    p['bmi'] = p['weight_kg'] / ((p['height_cm']/100)**2)
    p['physically_active'] = p['exercise_frequency'] != 'never'
    p['heavy_drinker'] = p['alcohol_use'] == 'frequent'
    return p

cases = {
    "A": patient_a,
    "B": dict(patient_a, smoking_status="current"),
    "C": dict(patient_a, smoking_status="current", high_bp=True, high_chol=True),
    "D": dict(patient_a, smoking_status="current", high_bp=True, high_chol=True, diabetes="diabetes", kidney_disease=True, copd=True, exercise_frequency="never", sleep_hours=4, general_health="poor", difficulty_walking=True, alcohol_use="frequent", physical_unwell_days=15),
}
cases["E"] = dict(cases["D"], age=75)

import warnings
warnings.filterwarnings('ignore')

for idx, (name, pt) in enumerate(cases.items()):
    val = to_ml_patient(pt)
    preds = predict_all(val)
    shaps = explain_all(val, top_k=3)
    
    print("="*60)
    print(f"CASE {name}")
    print("="*60)
    
    for d in ['heart_disease', 'kidney_disease', 'stroke']:
        print(f"--- {d.upper()} ---")
        p = preds[d]
        print(f"raw_probability: {p['raw_probability']:.4f}")
        print(f"corrected_probability: {p['probability']:.4f}")
        print(f"risk_level: {p['risk_level']}")
        
        s = shaps[d]
        print("top positive SHAP factors:")
        for factor in s.get("top_positive_factors", [])[:3]:
            print(f"  {factor['feature']}: {factor['shap_value']:.4f}")
            
        print("top negative SHAP factors:")
        for factor in s.get("top_negative_factors", [])[:3]:
            print(f"  {factor['feature']}: {factor['shap_value']:.4f}")
        print()
