export type RiskLevel = 'low' | 'moderate' | 'elevated' | 'high';

export interface PatientProfile {
  id: string;
  name: string;
  age: number;
  gender: string;
  height: number;
  weight: number;
  smoking: boolean;
  exerciseDaysPerWeek: number;
  lastUpdated: string;
}

export interface Factor {
  name: string;
  /** Raw XGBoost SHAP contribution in model-margin/log-odds space. */
  contribution: number;
  value?: string | number;
  direction?: 'increases_risk' | 'decreases_risk';
  importance?: 'high' | 'medium' | 'low';
  explanation?: string;
}

export interface DiseaseRisk {
  disease: string;
  riskPercentage: number;
  riskLevel: RiskLevel;
  /** Backend does not emit a calibrated confidence score — never use this to render UI. */
  confidence?: never;
  /** Backend does not provide a longitudinal trend. */
  trend?: 'increasing' | 'stable' | 'decreasing';
  headline?: string;
  shortExplanation?: string;
  /** Grounded context string from Health Agent (ML mode) or rule engine (rule_based mode). */
  riskContext?: string;
  /** Interaction rule labels that fired (rule_based mode only). */
  interactionRules?: string[];
  factors: Factor[];
  recommendations: string[];
}

export interface CarePlanAction {
  id: string;
  title: string;
  description: string;
  priority: number;
  type: 'doctor-reviewed' | 'ai-generated';
  completed: boolean;
}

export interface TrajectoryPoint {
  month: number;
  heart: number;
  kidney: number;
  stroke: number;
}

export interface LabInsight {
  test: string;
  value: string;
  unit: string | null;
  status: 'normal' | 'review' | 'important' | 'unverified';
  explanation: string;
}

export interface PatientReport {
  summary: string;
  risk_explanation: string;
  lab_summary: string;
  next_steps: string;
}

export interface DoctorSummary {
  clinical_overview: string;
  risk_summary: string;
  important_factors: string[];
  lab_points: string[];
  follow_up_points: string[];
}

export interface SpecialistFollowUp {
  recommended: boolean;
  reason: string;
}

export interface UIHints {
  overall_severity: RiskLevel;
  headline: string;
  show_attention_banner: boolean;
  priority_count: number;
}

export interface AssessmentData {
  patient: PatientProfile;
  overallRisk: RiskLevel;
  overallRiskSummary: string;
  risks: {
    heart: DiseaseRisk;
    kidney: DiseaseRisk;
    stroke: DiseaseRisk;
  };
  /** Empty until a genuine longitudinal model is implemented. */
  trajectory: TrajectoryPoint[];
  carePlan: CarePlanAction[];
  labInsights: LabInsight[];
  patientReport: PatientReport;
  doctorSummary: DoctorSummary;
  specialistFollowUp: SpecialistFollowUp;
  ui: UIHints;
  requestId?: string;
  /** 'ml' when the real backend was used, 'rule_based' when the fallback engine ran. */
  assessmentMode?: 'ml' | 'rule_based';
}

export const mockAssessment: AssessmentData = {
  patient: {
    id: 'PT-DEV',
    name: 'Patient',
    age: 45,
    gender: 'Male',
    height: 175,
    weight: 72,
    smoking: true,
    exerciseDaysPerWeek: 2,
    lastUpdated: new Date().toLocaleDateString(),
  },
  overallRisk: 'moderate',
  overallRiskSummary:
    'Development-only mock assessment. Live assessments are generated by the HealthTwin backend.',
  risks: {
    heart: {
      disease: 'Heart Disease',
      riskPercentage: 74,
      riskLevel: 'high',
      trend: 'increasing',
      factors: [{ name: 'Smoking', contribution: 0.21 }],
      recommendations: ['Increase weekly physical activity', 'Consider a smoking cessation program'],
    },
    kidney: {
      disease: 'Chronic Kidney Disease',
      riskPercentage: 48,
      riskLevel: 'moderate',
      trend: 'stable',
      factors: [{ name: 'High blood pressure', contribution: 0.15 }],
      recommendations: ['Monitor blood pressure', 'Discuss relevant screening with a clinician'],
    },
    stroke: {
      disease: 'Stroke',
      riskPercentage: 51,
      riskLevel: 'elevated',
      trend: 'stable',
      factors: [{ name: 'Smoking', contribution: 0.12 }],
      recommendations: ['Manage blood pressure', 'Increase cardiovascular exercise'],
    },
  },
  trajectory: [],
  carePlan: [
    {
      id: 'cp-1',
      title: 'Increase weekly physical activity',
      description: 'Aim for a consistent level of activity appropriate for you.',
      priority: 1,
      type: 'ai-generated',
      completed: false,
    },
  ],
  labInsights: [],
  patientReport: {
    summary: '',
    risk_explanation: '',
    lab_summary: '',
    next_steps: '',
  },
  doctorSummary: {
    clinical_overview: '',
    risk_summary: '',
    important_factors: [],
    lab_points: [],
    follow_up_points: [],
  },
  specialistFollowUp: {
    recommended: false,
    reason: '',
  },
  ui: {
    overall_severity: 'moderate',
    headline: 'Development mock data',
    show_attention_banner: false,
    priority_count: 1,
  },
};
